        name: Build-APK          # произвольное имя workflow

        on:
          push:
            tags: ['v*']         # триггер только при push тега v1.0.0, v1.1.3 …

        jobs:
          build:
            runs-on: ubuntu-latest

            steps:
            # 1. Клонируем репозиторий
            - uses: actions/checkout@v4

            # 2. Node.js + зависимости фронта/бэка
            - uses: actions/setup-node@v4
              with:
                node-version: '20'

            - run: npm ci
            - run: npx cap sync android          # копируем web‑код в android/

            # 3. JDK 21 (Capacitor требует Java 21)
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: '21'

            # 4. Android‑SDK + build‑tools
            - uses: android-actions/setup-android@v3

            # 5. Release‑сборка (unsigned)
            - name: Build unsigned APK
              run: |
                cd android
                ./gradlew assembleRelease

            # 6. Восстанавливаем keystore из секрета
            - name: Decode keystore
              run: echo "$KEYSTORE_B64" | base64 -d > keystore.jks
              env:
                KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

            # 7. Подписываем и zipalign (динамический поиск APK)
            - name: Sign and align
              run: |
                # ищем первый *release‑unsigned.apk
                APK=$(find android/app/build/outputs/apk/release -name '*release-unsigned.apk' | head -n 1)
                echo "Found APK: $APK"

                # подписываем
                jarsigner -verbose -keystore keystore.jks \
                  -storepass "$KS_PASS" -keypass "$KEY_PASS" \
                  "$APK" "$ALIAS"

                # zipalign
                ZIPALIGN="$ANDROID_HOME/build-tools/34.0.0/zipalign"
                OUT="Loans-${{ github.ref_name }}.apk"
                $ZIPALIGN -v 4 "$APK" "$OUT"
                echo "Aligned → $OUT"
              env:
                KS_PASS:  ${{ secrets.KEYSTORE_PASSWORD }}
                KEY_PASS: ${{ secrets.KEY_PASSWORD }}
                ALIAS:    ${{ secrets.KEY_ALIAS }}

            # 8. Публикуем артефакт
            - uses: actions/upload-artifact@v4
              with:
                name: apk
                path: Loans-*.apk