name: Build-APK-Latest

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - uses: actions/checkout@v4

    # 2. Устанавливаем Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Устанавливаем Java 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # 4. Выводим информацию о версиях для отладки
    - name: Debug environment
      run: |
        echo "Node version:"
        node --version
        echo "Java version:"
        java -version

    # 5. Установка NPM зависимостей
    - run: npm ci

    # 6. Подготовка проекта Capacitor
    - name: Prepare Capacitor project
      run: |
        # Подготовка проекта
        node prepare-for-apk.js
        
        # Переходим в директорию Capacitor
        cd capacitor-app
        
        # Устанавливаем зависимости
        npm install
        
        # Добавляем Android платформу
        npx cap add android
        
        # Копируем google-services.json, если он существует
        if [ -f "../capacitor-app/google-services.json" ]; then
          echo "Copying google-services.json to Android project"
          mkdir -p android/app/src/main
          cp ../capacitor-app/google-services.json android/app/google-services.json
        else
          echo "WARNING: google-services.json not found in capacitor-app directory!"
        fi
        
        # Обновляем gradle-wrapper.properties для использования Gradle 8.6
        mkdir -p android/gradle/wrapper
        echo "distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.6-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists" > android/gradle/wrapper/gradle-wrapper.properties
        
        # Настройка Java 21 в build.gradle, если он существует
        if [ -f "android/build.gradle" ]; then
          echo "// Add Java 21 compatibility settings to bottom of build.gradle
allprojects {
    tasks.withType(JavaCompile) {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}" >> android/build.gradle
        fi
        
        # Обновим еще один важный файл для совместимости с Java 21
        if [ -f "android/app/build.gradle" ]; then
          echo "// Add Java 21 compatibility settings to app/build.gradle
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}" >> android/app/build.gradle
        fi
        
        # Синхронизируем проект
        npx cap sync android
        
        # Возвращаемся в корневую директорию
        cd ..
        
        # Настраиваем канал уведомлений
        node setup-android-notification-channel.js

    # 7. Android SDK
    - uses: android-actions/setup-android@v3

    # 8. Сборка APK
    - name: Build unsigned APK
      run: |
        # Создадим директорию для google-services.json, если нужно
        mkdir -p capacitor-app/android/app/src/main
        
        # Копируем google-services.json в правильную директорию еще раз
        if [ -f "capacitor-app/google-services.json" ]; then
          echo "Copying google-services.json to Android project again"
          cp capacitor-app/google-services.json capacitor-app/android/app/google-services.json
        fi
        
        cd capacitor-app/android
        chmod +x ./gradlew
        
        # Для совместимости с Java 21 обновим gradle-wrapper скрипт
        sed -i 's/DEFAULT_JVM_OPTS=""/DEFAULT_JVM_OPTS="--add-opens java.base\/java.lang=ALL-UNNAMED --add-opens java.base\/java.io=ALL-UNNAMED --add-opens java.base\/java.util=ALL-UNNAMED"/g' gradlew
        
        # Соберем проект с более подробным выводом
        ./gradlew --stacktrace --info assembleRelease

    # 9. Восстанавливаем keystore из секрета
    - name: Decode keystore
      run: echo "$KEYSTORE_B64" | base64 -d > keystore.jks
      env:
        KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}

    # 10. Подписываем APK
    - name: Sign APK
      run: |
        # Находим APK
        UNSIGNED=$(find capacitor-app/android/app/build/outputs/apk/release -name '*release-unsigned.apk' | head -n 1)
        echo "Unsigned APK found at: $UNSIGNED"

        # Копируем во временный файл
        cp "$UNSIGNED" app-unsigned.apk

        # Подписываем
        APKSIGNER="$ANDROID_HOME/build-tools/34.0.0/apksigner"
        $APKSIGNER sign \
          --ks keystore.jks \
          --ks-key-alias "$ALIAS" \
          --ks-pass pass:"$KS_PASS" \
          --key-pass pass:"$KEY_PASS" \
          --out Loans-${{ github.ref_name }}.apk \
          app-unsigned.apk

        # Проверяем
        $APKSIGNER verify --verbose Loans-${{ github.ref_name }}.apk
      env:
        KS_PASS:  ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASS: ${{ secrets.KEY_PASSWORD }}
        ALIAS:    ${{ secrets.KEY_ALIAS }}

    # 11. Публикуем артефакт
    - uses: actions/upload-artifact@v4
      with:
        name: apk
        path: Loans-*.apk